### PR TITLE
Updating Folder and adding ReadME

### PR DESCRIPTION
**Pull request by amccann-Tek**
# Pull Request Checklist

Please review the [Contribution Guidelines](../README.md) before submitting.

- [x] Pulling against the `master` branch (left side).
- [x] You have previously submitted a [Contributor License Agreement](../README.md) or have contacted a maintainer to request one.

### Type (Select only one)

- [ ] Bug fix
- [X] Working example
- [ ] In-progress example (need Tektronix help)
- [ ] In-progress example (does not need Tektronix help)

### Description

Need a working link before we can publish application note, so wanted to get the folder set up for those purposes. The script itself will be uploaded later. READMEs will be updated later as well.

### CODE REVIEW

**Comment by amccann-Tek** [comment]
@adametry @dwyban is there any opportunity for review today?

**Comment by dwyban** [comment]
Hi @amccann-Tek .  The new readme file says to see the full write up on tek.com at the link below, but there is no link.

WBG-DPT Written Guide on Tek.com does not have a link on it.

**Comment by amccann-Tek** [comment]
@dwyban Correct. in a bit of a chicken and egg situation. They want to link here, we want to link there. Since files in here go through less review and publishing hoops I think we should stub ours out to get a link for them to include in their WBG app note. And then we can update these once published.

**Comment by dwyban** [comment]
@amccann-Tek , got it.  You're basically preparing the directory so we can have proper links.

Approving pull request.

**Pull request merged**
