### PR TITLE
Feature/dwyban/curvestream example complete code

### PR DESCRIPTION
**Pull request by dwyban**
# Pull Request Checklist

Please review the [Contribution Guidelines](../README.md#contributing) before submitting.

- [x] Pulling against the `develop` branch (left side).
- [x] You have previously submitted a [Contributor License Agreement](../README.md#CLA) or have contacted a maintainer to request one.

### Type (Select only one)

- [ ] Bug fix
- [x] Working example
- [ ] In-progress example (need Tektronix help)
- [ ] In-progress example (does not need Tektronix help)

### Description

This pull request updates the Curvestream Example with the complete Visual Studio project rather than just a single code file.  This will make it easier for people to use the example.  I also included an updated version of the example that uses the IVI standard VISA.NET library instead of NI-VISA.  NI's VisaNs is deprecated and should no longer be used.  VISA.NET is the vendor neutral VISA library that should be used in .NET applications.

### CODE REVIEW

**Comment by dwyban** [comment]
This PR addresses Issue #36

**Comment by dwyban** [comment]
It doesn't look like @bhensley86 @cbmurdock or @bit-lift want to review... :sob:

**Comment by zkoppert** [comment]
> It doesn't look like @bhensley86 @cbmurdock or @bit-lift want to review... 😭

They usually have a regular meeting to review these. @nlynchjo Do you know when the next meeting is?

**Comment by nlynchjo** [comment]
> 
> 
> > It doesn't look like @bhensley86 @cbmurdock or @bit-lift want to review... 😭
> 
> They usually have a regular meeting to review these. @nlynchjo Do you know when the next meeting is?

they were out of town this week, so it was cancelled 😭

**Comment by nlynchjo** [comment]
I think we are okay to merge this one

**Comment by dwyban** [comment]
Closes #36

**Pull request merged**
